site_name: 攻防对抗·蓝队清单

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'


extra:
  search:
    language: 'jp'

repo_url: https://github.com/satan1a/awesome-cybersecurity-blueteam-cn
repo_name: Toky/BlueTeam-CN